### ISSUE TITLE
Enhancement: Make sample rate configurable

### ISSUE THREAD

**Issue by wifwucite** [trvrnrth/esphome-bsec-bme680#14]
In BME680BSECComponent::setup the sample rate is fixed to BSEC_SAMPLE_RATE_LP. It would be nice to have an optional configuration which could change it to BSEC_SAMPLE_RATE_ULP to save power.

**Comment by gretel** [comment]
maybe this is worth mentioning https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BME680-BSEC-Samping-Rate/td-p/11413

**Comment by trvrnrth** [comment]
@gretel Yep; I've started adding support for the ULP mode but don't intend to add support for custom intervals on the basis of that guidance.

**Comment by gretel** [comment]
@trvrnrth thanks. i wasn't intending to say it's required or even useful :)

**Comment by wifwucite** [comment]
Thanks for the quick enhancement.

**Comment by trvrnrth** [comment]
@wifwucite No problem; this one was fairly straighforward. Hope it works out for you :)

**Comment by gretel** [comment]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/80815/103588825-5f1d4680-4eea-11eb-97ef-d9ec57ebd63e.png">
@trvrnrth works for me. thank you!

**Comment by trvrnrth** [comment]
@gretel Liking your choice of IAQ icon!
