### ISSUE TITLE
Not working with ESP32

### ISSUE THREAD

**Issue by nukleuz80** [trvrnrth/esphome-bsec-bme680#20]
Hi,

i tried the code in espHome with my new ESP32 DevKit v4. But i always get Zero (0) in the data back.

I dont get any errors in the compiling process.

espHome version: 1.5.3 

Thanks

**Comment by nukleuz80** [comment]
Now i´s working :)

**Comment by trvrnrth** [comment]
@nukleuz80 Glad you got things sorted :)
