### ISSUE TITLE
Implausible Measurements

### ISSUE THREAD

**Issue by lukasdietz** [trvrnrth/esphome-bsec-bme680#35]
Hey there,

I am trying to get a bme680 sensor up and running with this implementation of the bsec software. 
I am able to compile the code just fine but it seems to be impossible to get accurate values. 
After opening my Window for around 30 minutes values for co2 equivalent are almost at 2500 ppm and for VOC equivalent at around 10 ppm. This seems to be implausible to me because of the opened window.

Can someone tell me how to properly calibrate this sensor to get accurate readings from it? 
Is there an option to force a recalibration? 

I am hoping somebody can help me out.

**Comment by caddyblack** [comment]
Hi Lucas,

I have a MH-Z19 IR CO2 measurement near the bme680 to compare the results.
The resistivity of the bme680 was very low in the beginning. First week not
even s ove 30000 Ohm. The calculated CO2 was always far off.
After about 2 months the bme680 has stabilised. In clean air I get
resistivity values of 300000 Ohm with a calculated CO2 of 400 ppm.
I have tried with a high temperarure setting (400°C) but that did not help.
Now I have 1043 ppm CO2 on the bme680 and 743 ppm on the MH-Z19.
The VOC shows 9.8 ppm, a plausible value.
So use the bme680 for rough estimates only. The voc seems KK.
air pressure, humidity and temperature are very stable on the bme680 but
the offset of the temperature is 3.8°C!
Once tested and calibrated I only use it for the pressure, humidity and
temperature.
For CO2 measurements the bme680 is not accurate enough. You can use is to
determine rough estimates like 400-1500 ppm for normal indoor air and >2500
ppm you need extra airflow/ventilation.

Hope this information helpx you to judge the values you see.

Op zo 28 feb. 2021 18:15 schreef lukasdietz <notifications@github.com>:

**Comment by lukasdietz** [comment]
Hi,
I am glad someone did help me so fast! 
Thanks for your information. I am trying to build a "Covid ventilation alarm". Acoustic signal whenever it is needed to open a window. 
So if I understand you right I will have to give the sensor a quite long time to stabilize and use it for fairly accurate readings?
Would you say the IAQ values are accurate enough to make such an "alarm system"? 
Currently I am sitting around 200 for fresh air... 

![Screenshot_20210228-190351](https://user-images.githubusercontent.com/6624851/109428543-bece3480-79f7-11eb-9268-5823bd6d58e4.jpg)

These are my measurements for the last few hours.

**Comment by caddyblack** [comment]
Hi Lukas,

Please find my recent history graphs for comparison.


Op zo 28 feb. 2021 19:05 schreef lukasdietz <notifications@github.com>:

**Comment by lukasdietz** [comment]
Sorry for this question. Where do I find your history graphs?

**Comment by caddyblack** [comment]
> Sorry for this question. Where do I find your history graphs? 

See my previous answer with the links

**Comment by caddyblack** [comment]
> Sorry for this question. Where do I find your history graphs?

Reply in Github. Are pictures visible now?
![Screenshot_20210228-190958_Chrome](https://user-images.githubusercontent.com/48408773/109556382-08da1780-7ad7-11eb-9db3-5066c26312a3.jpg)
![Screenshot_20210228-191144_Chrome](https://user-images.githubusercontent.com/48408773/109556383-0972ae00-7ad7-11eb-9434-bb05aee42c6a.jpg)
![Screenshot_20210228-191224_Chrome](https://user-images.githubusercontent.com/48408773/109556384-0a0b4480-7ad7-11eb-8470-923bce452eab.jpg)
![Screenshot_20210228-191328_Chrome](https://user-images.githubusercontent.com/48408773/109556386-0a0b4480-7ad7-11eb-914a-691abde2ac5d.jpg)
![Screenshot_20210228-191420_Chrome](https://user-images.githubusercontent.com/48408773/109556387-0aa3db00-7ad7-11eb-9059-924c732bdae5.jpg)
![Screenshot_20210228-193149_Edge](https://user-images.githubusercontent.com/48408773/109556389-0aa3db00-7ad7-11eb-8cfd-ddec2bf84671.jpg)
Green is the MH-Z19 data, Yellow the BME680 calculated CO2 data.

**Comment by lukasdietz** [comment]
Yes now we can see your graphs!
Thanks for your help. Since yesterday the values seem to stabilize in a realistic value region.
Now I get IAQ values around 30.

**Comment by trvrnrth** [comment]
Interesting to see the comparison graphs. Doesn't seem like too bad an approximation once stable!

**Comment by rubinho101** [comment]
> Hi Lucas, I have a MH-Z19 IR CO2 measurement near the bme680 to compare the results. The resistivity of the bme680 was very low in the beginning. First week not even over 30000 Ohm. The calculated CO2 was always far off. After about 2 months the bme680 has stabilised. In clean air I get resistivity values of 300000 Ohm with a calculated CO2 of 400 ppm. I have tried with a high temperarure setting (400°C) in the first weeks but that did not help. Now I have 1043 ppm CO2 on the bme680 and 743 ppm on the MH-Z19. The VOC shows 9.8 ppm, a plausible value. So use the bme680 for rough estimates only. The voc seems OK. air pressure, humidity and temperature are very stable on the bme680 but the offset of the temperature is 3.8°C on my device! Once tested and calibrated I only use it for the pressure, humidity and temperature. For CO2 measurements the bme680 is not accurate enough. You can use is to determine rough estimates like 400-1500 ppm for normal indoor air and >2500 ppm you need extra airflow/ventilation. Hope this information helps you to judge the values you see. Op zo 28 feb. 2021 18:15 schreef lukasdietz <notifications@github.com>:
> […](#)

Would you recommend BME680 for VOC? What do you suggest for VOC?
