### ISSUE TITLE
Component not found: v    gas_resistance.

### ISSUE THREAD

**Issue by skywluke** [trvrnrth/esphome-bsec-bme680#38]
Hi! First of all thank you for your effort! I had a problem during validate: Failed config v    gas_resistance:   Component not found: v    gas_resistance. What is your oppinion? Thanks!

**Comment by trvrnrth** [comment]
If you post your config I can probably point out the issue.

**Comment by skywluke** [comment]
The BME680 one and only device on wemos d1 mini pro. I just copy everything from the your "Advanced configuration". Before that, these lines in the config:

esphome:
  name: wemos_3
  platform: ESP8266
  board: d1_mini

wifi:
manual_ip:
captive_portal:
logger:

i2c:
  scl: D1
  sda: D2
  scan: True
  id: bus_a

Many thanks!

**Comment by trvrnrth** [comment]
That should be fine then. Could you triple check the indenting?

**Comment by skywluke** [comment]
It was my mistake, Holded the previous config until the new isn't working with hash mark. And one of hashmark was "v" instead of #. Sorry.... and many thanks for support!

**Comment by trvrnrth** [comment]
Glad you got it sorted :)

**Comment by skywluke** [comment]
Yes, when i cheked the indenting i found the missed config piece. Many Thanks!
