### ISSUE TITLE
Communication failed

### ISSUE THREAD

**Issue by loefchen** [trvrnrth/esphome-bsec-bme680#43]
I'm fiddeling around with the configuration, but I'm permanently getting an error:

[bme680_bsec.sensor:135]: Communication failed (BSEC Status: 0, BME680 Status: -2)

It seems like one of my tries produced some values, but as I recognized it, it was too late and I could not reproduce it anymore.

I'm using a Wemos D1 mini with following I2C-config:

```
i2c:
  sda: 4
  scl: 5
```

The following config is is the example config from the readme.

Could anyone help?

**Comment by loefchen** [comment]
got it... Changed the adress from 0x76 to 0x77...

weird, I thought 0x76 should be standard.

**Comment by trvrnrth** [comment]
It'll depend on your board. Some appear to default to 0x76, some to 0x77.

Anyway, glad you got it sorted!
