### ISSUE TITLE
BSEC-BME680 does not compile in ESPHOME / Homeassistant

### ISSUE THREAD

**Issue by caddyblack** [trvrnrth/esphome-bsec-bme680#47]
Since the latest ESPHOME update I cannot compile without errors. Same code did compile before.
![Screenshot_20211023-163242_Chrome](https://user-images.githubusercontent.com/48408773/138561617-8154302c-865d-48db-91d7-61060e07d21c.jpg)

**Comment by trvrnrth** [comment]
Since the component is in core now you'll want to be using that version now (although I believe there might also be [an issue](https://github.com/esphome/issues/issues/2586) with the latest version there too at the moment!) as it should be in step with the latest changes.

**Comment by trvrnrth** [comment]
Just a quick update that I've checked up on the issue reported against the core component with the latest version and can't reproduce it so you should be good to go. I should perhaps make the note about using the core component now a bit bigger in the readme!

**Comment by caddyblack** [comment]
Indeed, by removing the bme680_bsec from the /esphome/custom_components directory the script now compiles OK.
Thanks for your feedback.
