### ISSUE TITLE
e-co2 problem

### ISSUE THREAD

**Issue by karaadam** [trvrnrth/esphome-bsec-bme680#9]
First of all thank you for the work. When the Voc value rises above 0.5, the co2 value becomes abnormal.
I can confirm this because I have an extra co2 sensor.

![co2](https://user-images.githubusercontent.com/42753464/101058543-4a255e80-359e-11eb-9757-473a7cbc0c29.png)

**Comment by trvrnrth** [comment]
Yeah, it's an estimate based on the values that the sensor actually measures. There's a bit more info in [this thread](https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/Explanation-on-static-IAQ-breath-VOC-and-CO2-equivalent/td-p/7413) and probably others in the forum if you want to delve into it a bit deeper. But I wouldn't expect it to be as accurate as your actual CO2 sensor!
